lsi: false
safe: true
source: ccportal/
incremental: false
include: [header, bootstrap, css, img, js, kt, less, plugins, bootstrap-table, dist, components, jquery, datatables, datatables-plugins]
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
